# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bettingtestframework < Formula
  desc ""
  homepage ""
  version "0.1.0"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/superbet-group/betting.test.framework/releases/download/v0.1.0/betting.test.framework_0.1.0_darwin_arm64.tar.gz"
      sha256 "220af975b0ed9823d1155c79a40673b4d8a3a459c656c209d8d30408ad4b9eff"

      def install
        bin.install "betctl"
        bash_completion.install "completions/betctl.bash" => "betctl"
        zsh_completion.install "completions/betctl.zsh" => "_betctl"
        fish_completion.install "completions/betctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/superbet-group/betting.test.framework/releases/download/v0.1.0/betting.test.framework_0.1.0_darwin_amd64.tar.gz"
      sha256 "8933f1affa1049710392309f87256f8f4852635ba8da23314337b187f98f8544"

      def install
        bin.install "betctl"
        bash_completion.install "completions/betctl.bash" => "betctl"
        zsh_completion.install "completions/betctl.zsh" => "_betctl"
        fish_completion.install "completions/betctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/superbet-group/betting.test.framework/releases/download/v0.1.0/betting.test.framework_0.1.0_linux_arm64.tar.gz"
      sha256 "cd38a12d47d2ff44c2055b7cea54ff53e4060066303de168f4b5ebf91ce32c05"

      def install
        bin.install "betctl"
        bash_completion.install "completions/betctl.bash" => "betctl"
        zsh_completion.install "completions/betctl.zsh" => "_betctl"
        fish_completion.install "completions/betctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/superbet-group/betting.test.framework/releases/download/v0.1.0/betting.test.framework_0.1.0_linux_amd64.tar.gz"
      sha256 "f264d5a7aed71bc91135ffbdaeb1ca09d5d88f47dad690b6dd6a6c3cdcc1ae22"

      def install
        bin.install "betctl"
        bash_completion.install "completions/betctl.bash" => "betctl"
        zsh_completion.install "completions/betctl.zsh" => "_betctl"
        fish_completion.install "completions/betctl.fish"
      end
    end
  end
end
