# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bettingtestframework < Formula
  desc ""
  homepage ""
  version "0.1.0"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/superbet-group/betting.test.framework/releases/download/v0.1.0/betting.test.framework_0.1.0_darwin_arm64.tar.gz"
      sha256 "c128e27e668fba1e85e7a61e1c3aefa9548b3afee3e8cc719f551f1cdcea7106"

      def install
        bin.install "betctl"
        bash_completion.install "completions/betctl.bash" => "betctl"
        zsh_completion.install "completions/betctl.zsh" => "_betctl"
        fish_completion.install "completions/betctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/superbet-group/betting.test.framework/releases/download/v0.1.0/betting.test.framework_0.1.0_darwin_amd64.tar.gz"
      sha256 "5a9fd2f5f18282018c79b630a681ee041f7c671bd06b5de2cd68599199a41dc5"

      def install
        bin.install "betctl"
        bash_completion.install "completions/betctl.bash" => "betctl"
        zsh_completion.install "completions/betctl.zsh" => "_betctl"
        fish_completion.install "completions/betctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/superbet-group/betting.test.framework/releases/download/v0.1.0/betting.test.framework_0.1.0_linux_arm64.tar.gz"
      sha256 "dbe5a060c989200aca9eff26ddfba24aded93f90f142121c5a72f0b378b6a9f3"

      def install
        bin.install "betctl"
        bash_completion.install "completions/betctl.bash" => "betctl"
        zsh_completion.install "completions/betctl.zsh" => "_betctl"
        fish_completion.install "completions/betctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/superbet-group/betting.test.framework/releases/download/v0.1.0/betting.test.framework_0.1.0_linux_amd64.tar.gz"
      sha256 "b815cfd0835d516d678beefcc7488e429b70bdf9288e2cc9e85c9c1936908ade"

      def install
        bin.install "betctl"
        bash_completion.install "completions/betctl.bash" => "betctl"
        zsh_completion.install "completions/betctl.zsh" => "_betctl"
        fish_completion.install "completions/betctl.fish"
      end
    end
  end
end
