# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Gamcli < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/superbet-group/gaming.common.cli/releases/download/v1.0.0/gamcli_1.0.0_macos_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ee04c45ef93bac78b2bc9c28ad4b753bbf76d72dcc21c10b5d8b6dd7689c589b"

      def install
        bin.install "gamcli"
        generate_completions_from_executable(bin/"gamcli", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/superbet-group/gaming.common.cli/releases/download/v1.0.0/gamcli_1.0.0_macos_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8989ea9437c46b96eab86974754f2268cdbe99fa9e105cd222e0caf0afa56fbb"

      def install
        bin.install "gamcli"
        generate_completions_from_executable(bin/"gamcli", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/superbet-group/gaming.common.cli/releases/download/v1.0.0/gamcli_1.0.0_linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "dcb2e2b6176417543b21cd6bbe13ddee0f8d113b5f9afc953bd037bb9eb4e73b"
      def install
        bin.install "gamcli"
        generate_completions_from_executable(bin/"gamcli", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/superbet-group/gaming.common.cli/releases/download/v1.0.0/gamcli_1.0.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "62f57f225c65701c591bbb2afea8c0b2d35c97507cd18bd503a11c3184effc31"
      def install
        bin.install "gamcli"
        generate_completions_from_executable(bin/"gamcli", "completion")
      end
    end
  end

  test do
    system "#{bin}/gamcli --help"
  end
end
