# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Gamcli < Formula
  desc ""
  homepage ""
  version "1.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/superbet-group/gaming.common.cli/releases/download/v1.3.0/gamcli_1.3.0_macos_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5ec3e110c397fb61b0e209b83d31297b9620bb115fe0217c011b69f882e133a8"

      def install
        bin.install "gamcli"
        generate_completions_from_executable(bin/"gamcli", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/superbet-group/gaming.common.cli/releases/download/v1.3.0/gamcli_1.3.0_macos_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2f5033c4f430b62f1cf882f224096ae432228c28c8195884d7e68561bf186372"

      def install
        bin.install "gamcli"
        generate_completions_from_executable(bin/"gamcli", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/superbet-group/gaming.common.cli/releases/download/v1.3.0/gamcli_1.3.0_linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "34fa7c89e42bcab50b6fa5d7687e77ddd84c448c282067429d047ef1f18bbb64"
      def install
        bin.install "gamcli"
        generate_completions_from_executable(bin/"gamcli", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/superbet-group/gaming.common.cli/releases/download/v1.3.0/gamcli_1.3.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "be2987296b3facd8a04faedb609083169b4a39a6b823c771f0b7893717ea435a"
      def install
        bin.install "gamcli"
        generate_completions_from_executable(bin/"gamcli", "completion")
      end
    end
  end

  test do
    system "#{bin}/gamcli --help"
  end
end
