# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Gincli < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/superbet-group/gaming.integration.cli/releases/download/v1.0.0/gincli_1.0.0_macos_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "bfe8a8518a630b05ce18dfe7a2d5310cc463258a1f094ad1293f997cbcd889bb"

      def install
        bin.install "gincli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/superbet-group/gaming.integration.cli/releases/download/v1.0.0/gincli_1.0.0_macos_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "93c6ca78bfe581cc13e380bad33300322a293b71060dc2cdf67a44ace9da37e3"

      def install
        bin.install "gincli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/superbet-group/gaming.integration.cli/releases/download/v1.0.0/gincli_1.0.0_linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c37588c7952dabb93bc43a1d1a5dadd840ebefd6d58a853130ae63f70148004b"
      def install
        bin.install "gincli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/superbet-group/gaming.integration.cli/releases/download/v1.0.0/gincli_1.0.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "258b9e183f6e8704d4db0744e4fa279a00c25b78c1da6a2295e2d17f7667bdb5"
      def install
        bin.install "gincli"
      end
    end
  end
end
