# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Gincli < Formula
  desc ""
  homepage ""
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/superbet-group/gaming.integration.cli/releases/download/v1.1.0/gincli_1.1.0_macos_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "750e85e26eba2e3e0c1cf4035ccb8d01d7f2d82979af919bf38ffcf2dfbc6ad6"

      def install
        bin.install "gincli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/superbet-group/gaming.integration.cli/releases/download/v1.1.0/gincli_1.1.0_macos_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1a8cf92449e9ea35f7086f7e7a3388ee3ceb4eb75c0f4da1bc5595331765fbd6"

      def install
        bin.install "gincli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/superbet-group/gaming.integration.cli/releases/download/v1.1.0/gincli_1.1.0_linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1fd593133bc1db4de358ad6b48de6ebd2210385b21c26c5739b07ba403592862"
      def install
        bin.install "gincli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/superbet-group/gaming.integration.cli/releases/download/v1.1.0/gincli_1.1.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c8f6be5c9bf0be01c9ea6cf5d7b15a12b000441ad6f29dfaa13e57b91f1f0dc7"
      def install
        bin.install "gincli"
      end
    end
  end
end
