# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Lola < Formula
  desc ""
  homepage ""
  version "0.0.27"

  on_macos do
    # on_intel do
    #   url "https://github.com/superbet-group/betting.test.framework/releases/download/v2.154.0/betctl_2.154.0_macos_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    #   sha256 "f8b07a50a6312a19f1e87ebf689e8010c774f6b433ca87250ba67e8da23b7c52"

    #   def install
    #     bin.install "betctl"
    #     prefix.install "betctl-p10k.zsh"
    #     generate_completions_from_executable(bin/"betctl", "completion")
    #   end
    # end
    on_arm do
      url "https://github.com/superbet-group/engprod.lola/releases/download/v0.0.27/lola-macos-arm64.bundle.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c6096304560508a31ffc7c871384db03a2dd9cd09d59701a8d6b448acef3c6cd"

      def install
        bin.install "lola/lola"
      end
    end
  end

  # on_linux do
  #   on_intel do
  #     if Hardware::CPU.is_64_bit?
  #       url "https://github.com/superbet-group/betting.test.framework/releases/download/v2.154.0/betctl_2.154.0_linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
  #       sha256 "1a48895f155a5836f95c618d440a0388e7fa0660dbf0e17e91fd552ec383fb97"

  #       def install
  #         bin.install "betctl"
  #         prefix.install "betctl-p10k.zsh"
  #         generate_completions_from_executable(bin/"betctl", "completion")
  #       end
  #     end
  #   end
  # end

  def caveats
    <<~EOS
      Seoska, najveća
      Seoska sam lola ja-a-a
      Seoska, najveća
      Seoska sam lola ja
    EOS
  end

  test do
    system "#{bin}/lola --help"
  end
end
