# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Orca < Formula
  desc "Orca - Offer platform CLI tool"
  homepage "https://github.com/superbet-group/offer.orca"
  version "1.83.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/superbet-group/offer.orca/releases/download/v1.83.0/orca_1.83.0_darwin_amd64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9a8b60a3a17f4914d6051fc4e830133d42a810cd6779e75243ef85ba88bb7e0f"

      def install
        bin.install "orca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/superbet-group/offer.orca/releases/download/v1.83.0/orca_1.83.0_darwin_arm64.zip", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8f72d9de958ee3cb5f87d757c8fe42082902fa75aaa3165fbfb0892ba96542ff"

      def install
        bin.install "orca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/superbet-group/offer.orca/releases/download/v1.83.0/orca_1.83.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5519e7083191478c706b59d0694429230110a442eaeac03a7a9409a709478b1e"
      def install
        bin.install "orca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/superbet-group/offer.orca/releases/download/v1.83.0/orca_1.83.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fbc954b6deab892fd8a156940d71df9df722303df6e34255e44cbe9cdd3f3343"
      def install
        bin.install "orca"
      end
    end
  end
end
