# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Riskctl < Formula
  desc ""
  homepage ""
  version "1.8.4"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/superbet-group/risk.cli/releases/download/v1.8.4/riskctl_1.8.4_macos_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "5c93e45d70ec1b558af301b83233aa97a1d1e62125ae4cd416344c2b963580a8"

    def install
      bin.install "riskctl"
      generate_completions_from_executable(bin/"riskctl", "completion")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/superbet-group/risk.cli/releases/download/v1.8.4/riskctl_1.8.4_macos_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "9a3a0f54eceef0355c7b3c193515c7aeffa64d1b8d8cb5b14465e152b25f474e"

    def install
      bin.install "riskctl"
      generate_completions_from_executable(bin/"riskctl", "completion")
    end
  end

  test do
    system "#{bin}/riskctl --help"
  end
end
