# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Riskctl < Formula
  desc ""
  homepage ""
  version "1.10.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/superbet-group/risk.cli/releases/download/v1.10.0/riskctl_1.10.0_macos_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "62fc31741dd0fd24be858862ac2af69ce864c4675a14a550193a3375cc8c38a3"

    def install
      bin.install "riskctl"
      generate_completions_from_executable(bin/"riskctl", "completion")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/superbet-group/risk.cli/releases/download/v1.10.0/riskctl_1.10.0_macos_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "2aa92534fe6ef6c912f622f3624b1529fcb58e30e8df02a0d0300fc97c9071ce"

    def install
      bin.install "riskctl"
      generate_completions_from_executable(bin/"riskctl", "completion")
    end
  end

  test do
    system "#{bin}/riskctl --help"
  end
end
