# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Riskctl < Formula
  desc ""
  homepage ""
  version "1.12.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/superbet-group/risk.cli/releases/download/v1.12.0/riskctl_1.12.0_macos_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "32119aab186993eb59a185f05246608fff1596634242c19fffb6a0f86710b332"

    define_method(:install) do
      bin.install "riskctl"
      generate_completions_from_executable(bin/"riskctl", "completion")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/superbet-group/risk.cli/releases/download/v1.12.0/riskctl_1.12.0_macos_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "2756f7f5c759f362caf99f5ca097d304e308f024c6c6d5362dbdfd0dd2bf48f3"

    define_method(:install) do
      bin.install "riskctl"
      generate_completions_from_executable(bin/"riskctl", "completion")
    end
  end

  test do
    system "#{bin}/riskctl --help"
  end
end
